backend/authentication/urls.py
from django.urls import path
from authentication.views import LoginView, RegisterView, UpdateView, ChangePassword, logout_view

app_name = 'authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('update/', UpdateView.as_view(), name='update'),
    path('change_password/<int:pk>/', ChangePassword.as_view(), name='change-password'),
    path('logout/', logout_view, name="logout"),
]

backend/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include,re_path  # add this
from django.conf import settings
from django.conf.urls.static import static
from core.views import admin_logout


urlpatterns = [
   path("admin/logout/", admin_logout, name='logout'), # Overwrite Logout admin view
   re_path(r'^admin/', (admin.site.urls)),
   path("auth/", include("authentication.urls", 'authentication')), # Auth routes - login / register
   path("", include("public.urls", 'public')),            # Public View
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

backend/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>EMPRESA TELEFONIA</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


{% block stylesheets %}
    <style> 
    </style> 
{% endblock stylesheets %}
</head>

<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'public:index'%}" class="navbar-brand d-flex align-items-center px-0 px-lg-0">
          {% if request.user.role == 512 %}
            {% if request.user.company_logo %}
              <h2 class="m-0 text-primary"><div class="text-center"><img src="{{ request.user.company_logo.url }}" class="rounded" alt="..." width="75" height="75"></div></h2>
            {% else %}
              <!--<h2 class="m-0 text-primary"><div class="text-center"><img src={% static "img/search.png" %} class="rounded" alt="..." width="75" height="75"></div></h2>-->
            {% endif %}
          {% else %}
            {% if request.user.administrator.company_logo %}
              <h2 class="m-0 text-primary"><div class="text-center"><img src="{{ request.user.administrator.company_logo.url }}" class="rounded" alt="..." width="75" height="75"></div></h2>
            {% endif %}
          {% endif %}
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto justify-content-right mb-md-0">
            <li><a href="{% url 'public:index' %}" class="nav-link px-2 link-secondary">Menu</a></li>
            <li><a href="{% url 'public:dashboard' %}" class="nav-link px-2 link-dark">Dashboard</a></li>
            {% if request.user.role < 512 %}
              <li><a href="{% url 'public:register-incidence'%}" class="nav-link px-2 link-dark">Registrar Incidencias</a></li>
              <li><a href="{% url 'public:incidences'%}" class="nav-link px-2 link-dark">Incidencias</a></li>
            {% else %}
              <li><a href={% url 'public:access-requests' %} class="nav-link px-2 link-dark">Solicitudes de acceso{% if notification_count > 0 %}<span class="translate-middle badge rounded-pill bg-danger">{{ notification_count }}</span>{%endif%}</a></li>
            {% endif %}
        </ul>

        <div class="dropdown text-end dropstart">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="true" data-toggle="dropdown" data-target="#navbarDropdown">
            {% if request.user.role == 512 %}
                <img src="{% static 'img/user_administrator.svg'%}" height='25px' width:'25px'>
            {% elif request.user.role == 255 %}
                <img src="{% static 'img/user_manager.svg'%}" height='25px' width:'25px'>
            {% else %}
                <img src="{% static 'img/user_employeer.svg'%}" height='25px' width:'25px'>
            {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start" aria-labelledby="navbarDropdown">
            <a href={% url 'public:configuration_user' %} class="list-group-item list-group-item-action">Perfil</a>
            <a href={% url 'public:configuration_user' %} class="list-group-item list-group-item-action">Configuración</a>
            <strong><a href={% url 'authentication:logout' %} class="list-group-item list-group-item-action">Cerrar sesión</a></strong>
          </ul>
        </div>
      </div>
    </div>
</header>
{% block content %}
{% endblock %}

<footer>
{% block javascripts %}
  <script src={% static "js/toggle.js" %}></script>
{% endblock javascripts %}
</footer>


    

backend/templates/base/public_base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>EMPRESA TELEFONIA</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->


{% block stylesheets %}
    <style> 
    </style> 
{% endblock stylesheets %}
</head>

<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'public:index'%}" class="navbar-brand d-flex align-items-center px-0 px-lg-0">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i></h2>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto justify-content-right mb-md-0">
            <li><a href="{% url 'public:index'%}" class="nav-link px-2 link-secondary">Inicio</a></li>
        </ul>

        <div class="text-end dropstart">
          <a href="#" class="d-block link-body-emphasis" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="true" data-toggle="dropdown" data-target="#navbarDropdown">
            <img src="{% static 'img/anonymous.svg'%}" height='25px' width:'25px'>
          </a>
        </div>
      </div>
    </div>
</header>
{% block content %}
{% endblock %}

<footer>
{% block javascripts %}
  <script src={% static "js/toggle.js" %}></script>
{% endblock javascripts %}
</footer>